In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_mumbai = pd.read_csv("../data/raw/zomato_res_final_f.csv",encoding="latin-1")

In [4]:
df_mumbai.head()

,Additional_outlet_count,Call,Cost_for_two,Cuisines,Features,Home_Delivery,Operational_hours,Restaurant_Location,Restaurant_Name,Restaurant_Type,...,Delivery_Time(mins),Rating,Votes,Rating_Category,Operational_after_Midnight,Cuisine_count,Feature_Count,Res_Type_Count,Competitors_in_Location,Score
0,2.0,True,250,Bakery,Food Hygiene Rated Restaurants In Mumbai,True,10am â 11pm (Mon-Sun),Airoli,Bake Ur Day,Bakery,...,60.0,4.0,308.0,Very Good,False,1,1,1,68.0,29.435336
1,9.0,True,300,"Bakery, Desserts",NaN,False,9am â 10pm (Mon-Sun),Airoli,Cake Street,Bakery,...,NaN,3.7,64.0,Good,False,2,1,1,68.0,23.822936
2,NaN,True,300,Bakery,NaN,True,10am â 11pm (Mon-Sun),Airoli,Tiers Of Joy,Bakery,...,136.0,4.0,156.0,Very Good,False,1,1,1,68.0,28.516814
3,NaN,True,500,"Cafe, Desserts",NaN,False,9am â 11pm (Mon-Sun),Airoli,FNP Cakes N More,Bakery,...,NaN,3.3,8.0,Average,False,2,1,2,68.0,17.967292
4,NaN,True,300,"Bakery, Desserts",Food Hygiene Rated Restaurants In Mumbai,True,9:30am â 12midnight (Mon-Sun),Airoli,Cake Boutique,Bakery,...,115.0,3.9,309.0,Good,False,2,1,2,68.0,28.062068

In [5]:
df_mumbai.shape

(5956, 22)

In [6]:
df_mumbai.columns.tolist()

['Additional_outlet_count',
 'Call',
 'Cost_for_two',
 'Cuisines',
 'Features',
 'Home_Delivery',
 'Operational_hours',
 'Restaurant_Location',
 'Restaurant_Name',
 'Restaurant_Type',
 'View_Menu',
 'Min_Order(Rs.)',
 'Delivery_Time(mins)',
 'Rating',
 'Votes',
 'Rating_Category',
 'Operational_after_Midnight',
 'Cuisine_count',
 'Feature_Count',
 'Res_Type_Count',
 'Competitors_in_Location',
 'Score']

In [7]:
df_mumbai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5956 entries, 0 to 5955
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Additional_outlet_count     833 non-null    float64
 1   Call                        5956 non-null   bool
 2   Cost_for_two                5956 non-null   int64
 3   Cuisines                    5956 non-null   object
 4   Features                    1232 non-null   object
 5   Home_Delivery               5956 non-null   bool
 6   Operational_hours           5950 non-null   object
 7   Restaurant_Location         5956 non-null   object
 8   Restaurant_Name             5956 non-null   object
 9   Restaurant_Type             5956 non-null   object
 10  View_Menu                   5956 non-null   bool
 11  Min_Order(Rs.)              2100 non-null   float64
 12  Delivery_Time(mins)         2100 non-null   float64
 13  Rating                      5956 non-null   float64
 14  Votes                       5956 non-null   float64
 15  Rating_Category             5956 non-null   object
 16  Operational_after_Midnight  5956 non-null   bool
 17  Cuisine_count               5956 non-null   int64
 18  Feature_Count               5956 non-null   int64
 19  Res_Type_Count              5956 non-null   int64
 20  Competitors_in_Location     5956 non-null   float64
 21  Score                       5956 non-null   float64
dtypes: bool(4), float64(7), int64(4), object(7)
memory usage: 861.0+ KB

In [8]:
df_mumbai.head()

,Additional_outlet_count,Call,Cost_for_two,Cuisines,Features,Home_Delivery,Operational_hours,Restaurant_Location,Restaurant_Name,Restaurant_Type,...,Delivery_Time(mins),Rating,Votes,Rating_Category,Operational_after_Midnight,Cuisine_count,Feature_Count,Res_Type_Count,Competitors_in_Location,Score
0,2.0,True,250,Bakery,Food Hygiene Rated Restaurants In Mumbai,True,10am â 11pm (Mon-Sun),Airoli,Bake Ur Day,Bakery,...,60.0,4.0,308.0,Very Good,False,1,1,1,68.0,29.435336
1,9.0,True,300,"Bakery, Desserts",NaN,False,9am â 10pm (Mon-Sun),Airoli,Cake Street,Bakery,...,NaN,3.7,64.0,Good,False,2,1,1,68.0,23.822936
2,NaN,True,300,Bakery,NaN,True,10am â 11pm (Mon-Sun),Airoli,Tiers Of Joy,Bakery,...,136.0,4.0,156.0,Very Good,False,1,1,1,68.0,28.516814
3,NaN,True,500,"Cafe, Desserts",NaN,False,9am â 11pm (Mon-Sun),Airoli,FNP Cakes N More,Bakery,...,NaN,3.3,8.0,Average,False,2,1,2,68.0,17.967292
4,NaN,True,300,"Bakery, Desserts",Food Hygiene Rated Restaurants In Mumbai,True,9:30am â 12midnight (Mon-Sun),Airoli,Cake Boutique,Bakery,...,115.0,3.9,309.0,Good,False,2,1,2,68.0,28.062068

In [9]:
missing = pd.DataFrame({
    "Missing Values": df_mumbai.isnull().sum(),
    "Missing %": (df_mumbai.isnull().sum() / len(df_mumbai) * 100).round(2)
})

missing.sort_values("Missing %", ascending=False)

                            Missing Values  Missing %
Additional_outlet_count               5123      86.01
Features                              4724      79.31
Delivery_Time(mins)                   3856      64.74
Min_Order(Rs.)                        3856      64.74
Operational_hours                        6       0.10
Cuisines                                 0       0.00
Votes                                    0       0.00
Competitors_in_Location                  0       0.00
Res_Type_Count                           0       0.00
Feature_Count                            0       0.00
Cuisine_count                            0       0.00
Operational_after_Midnight               0       0.00
Rating_Category                          0       0.00
Rating                                   0       0.00
Home_Delivery                            0       0.00
Cost_for_two                             0       0.00
Call                                     0       0.00
View_Menu                                0       0.00
Restaurant_Type                          0       0.00
Restaurant_Name                          0       0.00
Restaurant_Location                      0       0.00
Score                                    0       0.00

In [10]:
print("Duplicate rows:", df_mumbai.duplicated().sum())

Duplicate rows: 32

In [11]:
df_mumbai["Restaurant_Location"].nunique()

120

In [12]:
df_mumbai["Restaurant_Location"].value_counts().head(30)

Restaurant_Location
Thane West         360
Andheri West       245
Bandra West        204
Mira Road          198
Malad West         190
Borivali West      188
Chembur            136
Kalyan             124
Kandivali West     121
Dombivali East     120
Kharghar           119
Powai              113
Vasai              110
Vashi              109
Lower Parel        107
Mulund West        104
Juhu                94
Fort                93
Goregaon East       88
Vile Parle East     85
Chakala             81
Kandivali East      80
Colaba              78
Khar                75
Goregaon West       71
Nerul               69
Marol               68
Mahakali            67
Ghatkopar East      64
Santacruz East      61
Name: count, dtype: int64

In [13]:
keywords = ["Mumbai", "Navi Mumbai", "Thane", "Airoli"]

for keyword in keywords:
    mask = df_mumbai["Restaurant_Location"].astype(str).str.contains(
        keyword,
        case=False,
        na=False
    )
    
    print(f"{keyword}: {mask.sum()} restaurants")

Mumbai: 48 restaurants
Navi Mumbai: 0 restaurants
Thane: 371 restaurants
Airoli: 61 restaurants

In [14]:
df_mumbai[
    df_mumbai["Restaurant_Location"]
    .astype(str)
    .str.contains("Navi Mumbai", case=False, na=False)
]["Restaurant_Location"].value_counts()

Series([], Name: count, dtype: int64)

In [15]:
df_mumbai[
    df_mumbai["Restaurant_Location"]
    .astype(str)
    .str.contains("Thane", case=False, na=False)
]["Restaurant_Location"].value_counts()

Restaurant_Location
Thane West    360
Thane East     11
Name: count, dtype: int64

In [16]:
for col in [
    "Cuisines",
    "Rating",
    "Votes",
    "Cost_for_two",
    "Restaurant_Type"
]:
    if col in df_mumbai.columns:
        print(f"\n--- {col} ---")
        print(df_mumbai[col].head())

--- Cuisines ---
0              Bakery
1    Bakery, Desserts
2              Bakery
3      Cafe, Desserts
4    Bakery, Desserts
Name: Cuisines, dtype: object

--- Rating ---
0    4.0
1    3.7
2    4.0
3    3.3
4    3.9
Name: Rating, dtype: float64

--- Votes ---
0    308.0
1     64.0
2    156.0
3      8.0
4    309.0
Name: Votes, dtype: float64

--- Cost_for_two ---
0    250
1    300
2    300
3    500
4    300
Name: Cost_for_two, dtype: int64

--- Restaurant_Type ---
0    Bakery
1    Bakery
2    Bakery
3    Bakery
4    Bakery
Name: Restaurant_Type, dtype: object

In [17]:
df_mumbai.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Additional_outlet_count,833.0,NaN,NaN,NaN,4.669868,14.273269,1.0,1.0,1.0,3.0,262.0
Call,5956,1,True,5956,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cost_for_two,5956.0,NaN,NaN,NaN,667.374412,742.600576,50.0,350.0,500.0,700.0,30000.0
Cuisines,5956,2071,"North Indian, Chinese",258,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Features,1232,362,Food Hygiene Rated Restaurants In Mumbai,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Home_Delivery,5956,2,False,3856,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operational_hours,5950,1524,11am â 11pm (Mon-Sun),322,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Restaurant_Location,5956,120,Thane West,360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Restaurant_Name,5956,5637,Trupti,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Restaurant_Type,5956,7,Casual Dining,2940,NaN,NaN,NaN,NaN,NaN,NaN,NaN
View_Menu,5956,1,True,5956,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Min_Order(Rs.),2100.0,NaN,NaN,NaN,79.93619,53.415035,0.0,99.0,99.0,99.0,500.0
Delivery_Time(mins),2100.0,NaN,NaN,NaN,45.781429,31.646893,20.0,45.0,45.0,45.0,1440.0
Rating,5956.0,NaN,NaN,NaN,3.640497,0.39543,2.0,3.4,3.6,3.9,4.9
Votes,5956.0,NaN,NaN,NaN,276.803559,533.672936,2.0,35.0,98.0,279.0,9931.0
Rating_Category,5956,5,Good,3053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operational_after_Midnight,5956,2,False,4676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cuisine_count,5956.0,NaN,NaN,NaN,2.805406,1.564266,1.0,2.0,2.0,4.0,8.0
Feature_Count,5956.0,NaN,NaN,NaN,1.058428,0.316272,1.0,1.0,1.0,1.0,6.0
Res_Type_Count,5956.0,NaN,NaN,NaN,1.088146,0.283532,1.0,1.0,1.0,1.0,2.0
Competitors_in_Location,5956.0,NaN,NaN,NaN,119.039288,97.913124,1.0,45.0,91.0,148.0,386.0
Score,5956.0,NaN,NaN,NaN,24.288156,7.516902,1.057508,19.55055,23.647692,28.027704,90.344828

In [18]:
duplicates = df_mumbai[df_mumbai.duplicated(keep=False)]

duplicates.sort_values(
    ["Restaurant_Location", "Restaurant_Name"]
).head(20)

,Additional_outlet_count,Call,Cost_for_two,Cuisines,Features,Home_Delivery,Operational_hours,Restaurant_Location,Restaurant_Name,Restaurant_Type,...,Delivery_Time(mins),Rating,Votes,Rating_Category,Operational_after_Midnight,Cuisine_count,Feature_Count,Res_Type_Count,Competitors_in_Location,Score
4331,NaN,True,500,"North Indian, Chinese",20% off on all orders,True,"Closed (Mon),12noon â 3am (Tue-Sun)",Andheri West,Cinnamon N Nutmeg,Food Court,...,30.0,4.1,153.0,Very Good,True,2,1,1,295.0,29.877996
4333,NaN,True,500,"North Indian, Chinese",20% off on all orders,True,"Closed (Mon),12noon â 3am (Tue-Sun)",Andheri West,Cinnamon N Nutmeg,Food Court,...,30.0,4.1,153.0,Very Good,True,2,1,1,295.0,29.877996
4328,NaN,True,400,North Indian,Food Hygiene Rated Restaurants In Mumbai,True,"12noon â 4pm, 7pm â 3:30am (Mon-Sun)",Andheri West,Dilli Deli,Food Court,...,45.0,3.7,411.0,Good,True,1,1,1,295.0,25.919824
4329,NaN,True,400,North Indian,Food Hygiene Rated Restaurants In Mumbai,True,"12noon â 4pm, 7pm â 3:30am (Mon-Sun)",Andheri West,Dilli Deli,Food Court,...,45.0,3.7,411.0,Good,True,1,1,1,295.0,25.919824
278,NaN,True,1000,"Continental, Italian, Pizza, North Indian, Chi...",50% off on all orders above â¹500,True,"12midnight â 1:30am, 12noon â 12midnight (...",Andheri West,The Liquor Factory,Bar,...,45.0,3.9,818.0,Good,False,8,1,2,295.0,31.137907
279,NaN,True,1000,"Continental, Italian, Pizza, North Indian, Chi...",50% off on all orders above â¹500,True,"12midnight â 1:30am, 12noon â 12midnight (...",Andheri West,The Liquor Factory,Bar,...,45.0,3.9,818.0,Good,False,8,1,2,295.0,31.137907
575,NaN,True,300,"Continental, Fast Food, Beverages, Italian, Pizza",Food Hygiene Rated Restaurants In Mumbai,True,12noon â 12midnight (Mon-Sun),Borivali West,Dosti Yaari,CafÃ©,...,45.0,3.8,135.0,Good,False,5,1,1,193.0,25.631293
576,NaN,True,300,"Continental, Fast Food, Beverages, Italian, Pizza",Food Hygiene Rated Restaurants In Mumbai,True,12noon â 12midnight (Mon-Sun),Borivali West,Dosti Yaari,CafÃ©,...,45.0,3.8,135.0,Good,False,5,1,1,193.0,25.631293
1305,NaN,True,900,"Biryani, Beverages, Desserts, North Indian, Ch...",Food Hygiene Rated Restaurants In Mumbai,True,11:30am â 12:30AM (Mon-Sun),CBD-Belapur,Pranaam Fine Dine & Bar,Casual Dining,...,40.0,3.8,262.0,Good,True,5,1,2,58.0,26.398741
1306,NaN,True,900,"Biryani, Beverages, Desserts, North Indian, Ch...",Food Hygiene Rated Restaurants In Mumbai,True,11:30am â 12:30AM (Mon-Sun),CBD-Belapur,Pranaam Fine Dine & Bar,Casual Dining,...,40.0,3.8,262.0,Good,True,5,1,2,58.0,26.398741
4129,NaN,True,3500,Chinese,Best of Mumbai,False,7pm â 11:30pm (Mon-Sun),Chakala,Imperial China - Hilton Mumbai International A...,Fine Dining,...,NaN,4.5,149.0,Excellent,False,1,1,1,89.0,35.371066
4130,NaN,True,3500,Chinese,Best of Mumbai,False,7pm â 11:30pm (Mon-Sun),Chakala,Imperial China - Hilton Mumbai International A...,Fine Dining,...,NaN,4.5,149.0,Excellent,False,1,1,1,89.0,35.371066
4121,NaN,True,5000,"North Indian, Mughlai","Luxury Dining, Kebab Places",False,"12noon â 2:45pm, 7pm â 11:45pm (Mon-Sun)",Chakala,Peshawri - ITC Maratha,Fine Dining,...,NaN,4.4,1450.0,Very Good,False,2,2,1,89.0,41.853574
4122,NaN,True,5000,"North Indian, Mughlai","Luxury Dining, Kebab Places",False,"12noon â 2:45pm, 7pm â 11:45pm (Mon-Sun)",Chakala,Peshawri - ITC Maratha,Fine Dining,...,NaN,4.4,1450.0,Very Good,False,2,2,1,89.0,41.853574
4670,NaN,True,300,"Mughlai, Fast Food, Rolls",NaN,False,6:30pm â 11:45pm (Mon-Sun),Cuffe Parade,Idris Kebab & Rolls,Food Court,...,NaN,3.6,16.0,Good,False,3,1,1,13.0,22.153566
4671,NaN,True,300,"Mughlai, Fast Food, Rolls",NaN,False,6:30pm â 11:45pm (Mon-Sun),Cuffe Parade,Idris Kebab & Rolls,Food Court,...,NaN,3.6,16.0,Good,False,3,1,1,13.0,22.153566
623,NaN,True,1000,"Cafe, Continental, Italian",NaN,False,10:30am â 7:30pm (Mon-Sun),Fort,Food For Thought,CafÃ©,...,NaN,4.0,783.0,Very Good,False,3,1,1,95.0,32.305715
624,NaN,True,1000,"Cafe, Continental, Italian",NaN,False,10:30am â 7:30pm (Mon-Sun),Fort,Food For Thought,CafÃ©,...,NaN,4.0,783.0,Very Good,False,3,1,1,95.0,32.305715
4813,NaN,True,200,"Healthy Food, Street Food, Beverages, Fast Foo...",Food Hygiene Rated Restaurants In Mumbai,False,11am â 11pm (Mon-Sun),Ghatkopar West,Prayag Thali,Food Court,...,NaN,3.3,97.0,Average,False,7,1,1,54.0,18.505110
4814,NaN,True,200,"Healthy Food, Street Food, Beverages, Fast Foo...",Food Hygiene Rated Restaurants In Mumbai,False,11am â 11pm (Mon-Sun),Ghatkopar West,Prayag Thali,Food Court,...,NaN,3.3,97.0,Average,False,7,1,1,54.0,18.505110

In [19]:
df_mumbai[
    [
        "Restaurant_Name",
        "Restaurant_Location",
        "Restaurant_Type",
        "Cuisines",
        "Cost_for_two",
        "Rating",
        "Votes",
        "Home_Delivery",
        "Min_Order(Rs.)",
        "Delivery_Time(mins)"
    ]
].head(10)

,Restaurant_Name,Restaurant_Location,Restaurant_Type,Cuisines,Cost_for_two,Rating,Votes,Home_Delivery,Min_Order(Rs.),Delivery_Time(mins)
0,Bake Ur Day,Airoli,Bakery,Bakery,250,4.0,308.0,True,0.0,60.0
1,Cake Street,Airoli,Bakery,"Bakery, Desserts",300,3.7,64.0,False,NaN,NaN
2,Tiers Of Joy,Airoli,Bakery,Bakery,300,4.0,156.0,True,0.0,136.0
3,FNP Cakes N More,Airoli,Bakery,"Cafe, Desserts",500,3.3,8.0,False,NaN,NaN
4,Cake Boutique,Airoli,Bakery,"Bakery, Desserts",300,3.9,309.0,True,99.0,115.0
5,Top In Town Bakery,Ambernath,Bakery,"Bakery, Fast Food",400,3.3,10.0,False,NaN,NaN
6,Cakers & Cakers,Andheri West,Bakery,Bakery,300,4.2,233.0,True,99.0,60.0
7,Cookie me up,Andheri West,Bakery,Bakery,300,3.6,25.0,False,NaN,NaN
8,New Super Sweets,Andheri West,Bakery,"Bakery, Desserts",200,3.8,78.0,True,0.0,45.0
9,Cake Tree,Andheri West,Bakery,"Bakery, Desserts",350,3.2,64.0,True,99.0,45.0

In [20]:
# Check duplicate rows
print("Duplicate rows:", df_mumbai.duplicated().sum())

# Remove exact duplicates
df_clean = df_mumbai.drop_duplicates().copy()

print("Original shape:", df_mumbai.shape)
print("Cleaned shape:", df_clean.shape)

Duplicate rows: 32
Original shape: (5956, 22)
Cleaned shape: (5924, 22)

In [21]:
df_clean = df_clean.drop(
    columns=["Additional_outlet_count", "Features"]
)

print(df_clean.shape)

(5924, 20)

In [22]:
missing = pd.DataFrame({
    "Missing Values": df_clean.isnull().sum(),
    "Missing %": (df_clean.isnull().sum() / len(df_clean) * 100).round(2)
})

missing = missing[missing["Missing Values"] > 0] \
    .sort_values("Missing %", ascending=False)

missing

                     Missing Values  Missing %
Min_Order(Rs.)                 3836      64.75
Delivery_Time(mins)            3836      64.75
Operational_hours                 6       0.10

In [23]:
df_clean[
    ["Home_Delivery", "Min_Order(Rs.)", "Delivery_Time(mins)"]
].isnull().sum()

Home_Delivery             0
Min_Order(Rs.)         3836
Delivery_Time(mins)    3836
dtype: int64

In [24]:
pd.crosstab(
    df_clean["Home_Delivery"],
    df_clean["Delivery_Time(mins)"].isnull()
)

Delivery_Time(mins)  False  True
Home_Delivery
False                    0   3836
True                  2088      0

In [25]:
pd.crosstab(
    df_clean["Home_Delivery"],
    [
        df_clean["Min_Order(Rs.)"].isnull(),
        df_clean["Delivery_Time(mins)"].isnull()
    ]
)

Min_Order(Rs.)      False True
Delivery_Time(mins) False True
Home_Delivery
False                   0  3836
True                 2088     0

In [26]:
df_clean.groupby("Home_Delivery")[[
    "Min_Order(Rs.)",
    "Delivery_Time(mins)"
]].agg(["count", "mean", "median", "min", "max"])

              Min_Order(Rs.)                              Delivery_Time(mins)  \
                       count      mean median  min    max               count
Home_Delivery
False                      0       NaN    NaN  NaN    NaN                   0
True                    2088  79.96887   99.0  0.0  500.0                2088


                    mean median   min     max
Home_Delivery
False                NaN    NaN   NaN     NaN
True           45.795498   45.0  20.0  1440.0

In [27]:
# Missing delivery-related values are structurally missing
# because these restaurants do not offer home delivery.

df_clean[["Home_Delivery", "Min_Order(Rs.)", "Delivery_Time(mins)"]].isnull().sum()

Home_Delivery             0
Min_Order(Rs.)         3836
Delivery_Time(mins)    3836
dtype: int64

In [28]:
df_clean["Min_Order_Applicable"] = df_clean["Home_Delivery"]
df_clean["Delivery_Time_Applicable"] = df_clean["Home_Delivery"]